---
title: "Stream_stats"
author: "Josh Erickson"
date: "September 27, 2020"
output: html_document
---

Downloading Stream Stats data.

```{r}
library(tidyverse)
library(rgdal)
library(streamstats)
library(sf)
library(tidyverse)
library(geojsonsf)
library(feather)

usgs_raws <- read_feather("D:/R_folder/Apps/hydroclimatic_app/app_build/mapping_usgs.csv")
usgs_raws <- usgs_raws %>% mutate(
             drainage_area_cut = cut(drainage_area, breaks =  c(0,15,25,50,75,100, 150,300, 400, 600, 800, 1000, 2000, 5000, Inf), dig.lab = 10),
             drainage_area_cut = str_remove_all(drainage_area_cut, c("\\[|\\]" = "", "\\(|\\)" = "", "," = "-")),
             drainage_area_cut = factor(drainage_area_cut, levels = c("0-15", "15-25", "25-50","50-75" , "75-100", "100-150", "150-300", "300-400", "400-600", "600-800", "800-1000", "1000-2000", "2000-5000", "5000-Inf")))

usgs_raws %>% count(drainage_area_cut, sort = T)

watersheds_MT <- usgs_raws %>% filter(str_detect(Station, "MT")) %>% group_by(Station) %>% 
  select(lat, long) %>% nest() %>% 
  mutate(ws = map(data,~tryCatch(delineateWatershed(.$long,.$lat , rcode = "MT", crs = 4326), error=function(e){cat("ERROR :",conditionMessage(e), "\n")})))

usgs_ws_polys <- tibble()
usgs_flow_stats <- tibble()

for (i in 1:nrow(watersheds_MT)) {
tryCatch({
usgs_ws <- pluck(watersheds_MT$ws) %>% pluck(i)  %>%  
  writeGeoJSON(., "D:/R_folder/Apps/hydroclimatic_app/watershed.geojson") %>%
  geojson_sf()
usgs_ws$Name <- pluck(watersheds_MT$Station) %>% pluck(i) %>% paste()

usgs_ws_polys <- plyr::rbind.fill(usgs_ws_polys, usgs_ws)

flow_stats <- streamstats::computeChars(workspaceID = watersheds_MT$ws[[i]]$workspaceID, rcode = "MT")

flow_stats <- flow_stats$parameters

flow_stats$Station <- pluck(watersheds_MT$Station) %>% pluck(i) %>% paste()

usgs_flow_stats <- plyr::rbind.fill(usgs_flow_stats, flow_stats)

}, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})

}

usgs_ws_polys_MT <- usgs_ws_polys %>% st_as_sf()
ggplot() + geom_sf(data = usgs_ws_polys$geometry, aes( fill = Station), show.legend = FALSE)

usgs_flow_stats_MT <- usgs_flow_stats %>% select(code, value, Station) %>% pivot_wider(names_from = code, values_from = value)

usgs_poly_MT_fs <- usgs_ws_polys_MT %>% select(Station, HUCID) %>% left_join(usgs_flow_stats_MT, by = "Station")

write_feather(usgs_flow_stats_MT, "D:/R_folder/Apps/hydroclimatic_app/app_build/usgs_flow_stats_MT.csv")

write_sf(usgs_ws_polys_MT, "D:/R_folder/Apps/hydroclimatic_app",
          layer = "usgs_ws_polys_MT", driver = "ESRI Shapefile")

write_sf(usgs_poly_MT_fs, "D:/R_folder/Apps/hydroclimatic_app",
          layer = "usgs_poly_MT_fs", driver = "ESRI Shapefile")
```

Now for idaho. let's only take what's in the region.

```{r}
library(feather)
usgs_min_max_wy <- read_feather("D:/R_folder/Apps/hydroclimatic_app/app_build/usgs_min_max_wy.csv")

usgs_mapping <- read_feather("D:/R_folder/Apps/hydroclimatic_app/app_build/mapping_usgs.csv")
ownership <- read_sf("D:/R_folder/Apps/hydroclimatic_app/Basic_Owndership_export.shp")
glimpse(ownership)
region_01 <- ownership %>% filter(REGION == "01") %>% st_set_crs(4326) %>% st_transform(4326)
watersheds_ID <- usgs_mapping %>% filter(str_detect(Station, "ID")) %>% st_as_sf(coords = c("long", "lat")) %>% st_set_crs(4326)



```

```{r}
watersheds_ID <- usgs_mapping %>% filter(str_detect(Station, "ID")) %>% group_by(Station) %>% 
  select(lat, long) %>% nest() %>% 
  mutate(ws = map(data,~tryCatch(delineateWatershed(.$long,.$lat , rcode = "ID", crs = 4326), error=function(e){cat("ERROR :",conditionMessage(e), "\n")})))

usgs_ws_polys_id <- tibble()
usgs_flow_stats_id <- tibble()

for (i in 1:nrow(watersheds_ID)) {
tryCatch({
usgs_ws <- pluck(watersheds_ID$ws) %>% pluck(i)  %>%  
  writeGeoJSON(., "D:/R_folder/Apps/hydroclimatic_app/watershed.geojson") %>%
  geojson_sf()
usgs_ws$Name <- pluck(watersheds_ID$Station) %>% pluck(i) %>% paste()

usgs_ws_polys_id <- plyr::rbind.fill(usgs_ws_polys_id, usgs_ws)

flow_stats <- streamstats::computeChars(workspaceID = watersheds_ID$ws[[i]]$workspaceID, rcode = "ID")

flow_stats <- flow_stats$parameters

flow_stats$Station <- pluck(watersheds_ID$Station) %>% pluck(i) %>% paste()

usgs_flow_stats_id <- plyr::rbind.fill(usgs_flow_stats_id, flow_stats)

}, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})

}

usgs_ws_polys_id_final <- usgs_ws_polys_id %>% st_as_sf()
ggplot() + geom_sf(data = usgs_ws_polys_id_final, aes(fill = Name), show.legend = FALSE)

usgs_flow_stats_id_final <- usgs_flow_stats_id %>% select(code, value, Station) %>% pivot_wider(names_from = code, values_from = value)

usgs_poly_ID_fs <- usgs_ws_polys_id %>% select(Name, HUCID) %>% rename(Station = "Name") %>%  left_join(usgs_flow_stats_id_final, by = "Station")

write_feather(usgs_flow_stats_id_final, "D:/R_folder/Apps/hydroclimatic_app/app_build/usgs_flow_stats_id_final.csv")

write_sf(usgs_ws_polys_id_final, "D:/R_folder/Apps/hydroclimatic_app",
          layer = "usgs_ws_polys_id_final", driver = "ESRI Shapefile")

write_sf(usgs_poly_ID_fs, "D:/R_folder/Apps/hydroclimatic_app",
          layer = "usgs_poly_ID_fs", driver = "ESRI Shapefile")
```


